# Install OMERO.server and OMERO.web with a public user on localhost

- hosts: all
  pre_tasks:

    - name: Install Make Movie script Prerequisite | MEncoder - Repo
      become: yes
      yum:
        name:  http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
        state: present

    - name: Install Make Movie script Prerequisite | MEncoder - Package
      become: yes
      yum:
        name: mencoder
        state: present

    - name: OMERO.figure server-side prerequisites, script prerequisites + web server for decoupled OMERO.web
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        # For OMERO.figure
        - python-reportlab
        - python-markdown
        # For the 'make movie' script
        - mencoder
        - scipy

  roles:

    - role: openmicroscopy.postgresql
      postgresql_databases:
      - name: omero
      postgresql_users:
      - user: omero
        password: omero
        databases: [omero]
      postgresql_version: "9.6"

    - role: openmicroscopy.omero-server
      omero_server_release: 5.4.1

    - role: openmicroscopy.omero-web
      omero_web_release: 5.4.1
      # omero_web_config_set:

  post_tasks:
    - name: Omero.web plugins | plugin install via pip & pypi
      become: yes
      pip:
        name:
        - "omero-figure==3.1.2"
        - "omero-fpbioimage==0.2.0"
        - "omero-webtagging-autotag==3.0.2"
        - "omero-webtagging-tagsearch==3.0.3"
        - "omero-iviewer==0.4.1"
        editable: False
        state: present
        # variable comes from role openmicroscopy.omero-web
        virtualenv: "{{ omero_web_basedir }}/venv"
        virtualenv_site_packages: yes
      notify:
        - restart omero-web

    - name: Create a figure scripts directory
      become: yes
      file:
        path: /opt/omero/server/OMERO.server/lib/scripts/omero/figure_scripts
        state: directory
        mode: 0755
        recurse: yes
        owner: "omero-server"
        group: "omero-server"

    - name: Download the Figure_To_Pdf.py script
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/ome/omero-figure/v3.1.2/omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
        dest: /opt/omero/server/OMERO.server/lib/scripts/omero/figure_scripts/Figure_To_Pdf.py
        mode: 0755
        owner: "omero-server"
        group: "omero-server"

    - name: Create a cambridge_scripts directory
      become: yes
      file:
        path: /opt/omero/server/OMERO.server/lib/scripts/omero/cambridge_scripts
        state: directory
        mode: 0755
        recurse: yes
        owner: "omero-server"
        group: "omero-server"

    - name: Download the Scipy_Gaussian_Filter.py script
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/jburel/omero-example-scripts/cambridge-training/cambridge-training-2017-12/Scipy_Gaussian_Filter.py
        dest: /opt/omero/server/OMERO.server/lib/scripts/omero/cambridge_scripts/Scipy_Gaussian_Filter.py
        mode: 0755
        owner: "omero-server"
        group: "omero-server"
        force: yes

    - name: Add DropBox folder for trainer-1
      become: yes
      file:
        path: /OMERO/DropBox/trainer-1
        state: directory
        mode: 0755
        recurse: yes
        owner: "omero-server"
        group: "omero-server"

    - name: Add DropBox folders for user-1 to user-40
      become: true
      file:
        path: /OMERO/DropBox/{{ item }}
        state: directory
        mode: 0775
        owner: "omero-server"
        group: "omero-server"
      with_sequence: start=1 end=40 format=user-%d

    # Config for OMERO.web plugins, loaded into OMERO.web by the
    # omero.web systemd restart.
    - name: Config for OMERO.web plugins
      become: yes
      template:
        src: omero-web-config-for-webapps.j2
        dest: "{{ omero_web_basedir }}/config/omero-web-config-for-webapps.omero"
        owner: "root"
        group: "root"
        mode: "u=rw,go=r"
      notify:
      - restart omero-web

    - name: Set default viewer in OMERO.web
      become: yes
      template:
        src: omero-web-config-default-viewer.j2
        dest: "{{ omero_web_basedir }}/config/omero-web-config-default-viewer.omero"
        owner: "root"
        group: "root"
        mode: "u=rw,go=r"
      notify:
      - restart omero-web

  vars:
    omero_web_public_password: public
    omero_server_config_set:
      omero.jvmcfg.percent.blitz: 50
      omero.jvmcfg.percent.indexer: 20
      omero.jvmcfg.percent.pixeldata: 20
